---
- name: Deploy Dockerized Web Application
  hosts: demo
  become: true

  tasks:
    - name: Copy docker-compose.yml to remote server
      copy:
        src: docker-compose.yml
        dest: .

    - name: Copy Dockerfile and context to remote server
      copy:
        src: Dockerfile
        dest: .

    - name: Copy nginx configuration template to remote server
      copy:
        src: nginx.conf.j2
        dest: .

    - name: Copy src dir
      copy:
        src: ./src
        dest: .

    - name: Build custom PHP image
      command: docker build -t php_image .
      args:
        chdir: .

    - name: Start services with Docker Compose
      command: docker-compose up --build -d

    - name: Copy nginx configuration file to Nginx container
      community.docker.docker_container_copy_into:
        container: nginx
        path: nginx.conf.j2
        container_path: /etc/nginx/conf.d/default.conf


    - name: Restart Nginx service inside the container
      community.docker.docker_container:
        name: nginx
        state: started
        restart_policy: always
        recreate: true
        timeout: 60


