version: '3'

services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    volumes:
      - ./nginx.conf.j2:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my-network

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

